# Workflow name
name: Deploy to production

# On which events to run the jobs
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      - name: connecting to server with sssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd ~/projects/github/cicd-boilerplate
            ./scripts/before-deploy.sh
            ./scripts/depoy-backend.sh
            ./scripts/deploy-frontend.sh
            ./scripts/after-deploy.sh
